### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by icrosil** [NikhilKalige/git-log#49] opened 2015-03-23 16:25 UTC
[Enter steps to reproduce below:]

1. showing git-log in git repo

**Atom Version**: 0.187.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [git-log](https://github.com/nikhilkalige/git-log) package, v0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At C:\Users\user\.atom\packages\git-log\lib\logparser.js:116

TypeError: Cannot read property 'split' of null
  at parse_git_log (C:\Users\user\.atom\packages\git-log\lib\logparser.js:116:20)
  at GitLogView.parser (C:\Users\user\.atom\packages\git-log\lib\git-log-view.js:110:16)
  at GitLogView.log_callback (C:\Users\user\.atom\packages\git-log\lib\git-log-view.js:68:10)
  at C:\Users\user\.atom\packages\git-log\lib\git-log-view.js:50:18
  at BufferedProcess.triggerExitCallback (C:\Users\user\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (C:\Users\user\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
  3x -0:17.1 click (atom-text-editor.editor)
     -0:09.2 command-palette:toggle (atom-text-editor.editor)
     -0:05.5 core:confirm (atom-text-editor.editor.mini)
     -0:05.5 git-log:show (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "followSymlinks": true,
    "disabledPackages": [
      "deprecation-cop",
      "whitespace",
      "neon-selection",
      "atom-pair",
      "git-go",
      "git-plus"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
atomatigit, v1.2.3
autocomplete-plus, v2.2.0
color-picker, v1.5.0
docblockr, v0.6.3
emmet, v2.3.4
git-log, v0.3.0
highlight-line, v0.10.1
jshint, v1.3.0
keybinding-cheatsheet, v0.0.8
linter, v0.12.0
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-jsonlint, v0.1.2
linter-less, v0.3.1
minimap, v4.6.0
minimap-bookmarks, v0.1.0
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
minimap-selection, v4.2.0
open-last-project, v0.3.5
project-manager, v1.15.5
rainbow-selection, v0.3.0
Search, v0.4.0
select-line, v0.16.0
seti-syntax, v0.3.3
seti-ui, v0.6.3
Sublime-Style-Column-Selection, v1.2.3
symbols-tree-view, v0.8.2
sync-settings, v0.2.2
tabs-to-spaces, v0.9.0
trailing-spaces, v0.2.4

# Dev
No dev packages
```

**Comment by kobakou** [comment] 2015-03-29 02:21
Sorry, I mistook to make issue. please close it. This issue has been occured with internal gitlab server.

**Closed** 2015-03-30 13:47 UTC

**Comment by hayatofujii** [comment] 2015-03-31 14:34
Uh, I don't see why this issue should be closed, as is still prevails (at least on my envirovment).
This seems to be caused mostly on Windows, as on a similar setup on a Linux machine, the plugin works as intended.

**Comment by icrosil** [comment] 2015-03-31 14:41
Surely log says that problem isn`t in package itself. Atom trying to use windows console to find git projects to pull it through Atom to package. My problem was based on cmd autorun, i edited my registr like .../somewhere/console_prompt_like/Autorun <string> = "cd \d f:\some\path". After erasing this string, problem dissapeared.

**Comment by Quantumplation** [comment] 2015-04-19 01:39
This is also occurring on my machine, also Windows.

Reproduce:

1. Install package
2. Ctrl+Shift+P
3. Git Log: Show
4. Exception occurs.

**Atom Version**: 0.190.0
**System**: Microsoft Windows 8.1
**Thrown From**: [git-log](https://github.com/nikhilkalige/git-log) package, v0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At C:\Users\Pi\.atom\packages\git-log\lib\logparser.js:116

TypeError: Cannot read property 'split' of null
  at parse_git_log (C:\Users\Pi\.atom\packages\git-log\lib\logparser.js:116:20)
  at GitLogView.parser (C:\Users\Pi\.atom\packages\git-log\lib\git-log-view.js:110:16)
  at GitLogView.log_callback (C:\Users\Pi\.atom\packages\git-log\lib\git-log-view.js:68:10)
  at C:\Users\Pi\.atom\packages\git-log\lib\git-log-view.js:50:18
  at BufferedProcess.triggerExitCallback (C:\Users\Pi\AppData\Local\atom\app-0.190.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (C:\Users\Pi\AppData\Local\atom\app-0.190.0\resources\app\src\buffered-process.js:85:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -7:02.7 application:open-file (atom-pane.pane.active)
     -6:57.9 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode)
     -6:55.8 core:confirm (atom-text-editor.editor.mini)
     -6:55.8 git-log:show (atom-text-editor.editor.vim-mode.command-mode)
     -5:43.7 core:cancel (div.git-log)
     -0:04.4 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
     -0:02.8 core:confirm (atom-text-editor.editor.mini)
     -0:02.8 git-log:show (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "git-log": {}
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.6
autoclose-html, v0.15.0
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.11.0
git-log, v0.3.0
linter, v0.12.0
minimap, v4.7.6
vim-mode, v0.44.0

# Dev
No dev packages
```

**Comment by Quantumplation** [comment] 2015-04-19 02:12
My path variable did not contain the Git bin folder.  I suspect this is the case for many people who install msysgit.  This package relies on git being in the path.  As soon as I corrected this, the package (and several other packages involving git) began working.

**Comment by suread** [comment] 2015-04-21 18:02
I am seeing the same error if I try and use Git Log on a repo with no commits. If I then make a commit, Git Log runs with no problems.

[Enter steps to reproduce below:]

1. Open project in Atom - have performed git init, but no files have been staged/committed
2. select Git Log: show from command list

**Atom Version**: 0.192.0
**System**: Microsoft Windows 8.1
**Thrown From**: [git-log](https://github.com/nikhilkalige/git-log) package, v0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At C:\Users\xxx\.atom\packages\git-log\lib\logparser.js:116

TypeError: Cannot read property 'split' of null
  at parse_git_log (C:\Users\xxx\.atom\packages\git-log\lib\logparser.js:116:20)
  at GitLogView.parser (C:\Users\xxx\.atom\packages\git-log\lib\git-log-view.js:110:16)
  at GitLogView.log_callback (C:\Users\xxx\.atom\packages\git-log\lib\git-log-view.js:68:10)
  at C:\Users\xxx\.atom\packages\git-log\lib\git-log-view.js:50:18
  at BufferedProcess.triggerExitCallback (C:\Users\xxx\AppData\Local\atom\app-0.192.0\resources\app\src\buffered-process.js:63:47)
  at C:\Users\xxx\AppData\Local\atom\app-0.192.0\resources\app\src\buffered-process.js:77:18
  at Socket.<anonymous> (C:\Users\xxx\AppData\Local\atom\app-0.192.0\resources\app\src\buffered-process.js:150:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -1:13.4 application:add-project-folder (atom-text-editor.editor)
  4x -1:02.5 core:backspace (atom-text-editor.editor)
     -0:34.9 command-palette:toggle (atom-text-editor.editor)
  4x -0:32.8 core:move-up (atom-text-editor.editor.mini)
     -0:28.3 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:28.3 core:cancel (atom-text-editor.editor.mini)
     -0:23.6 command-palette:toggle (atom-text-editor.editor)
  2x -0:14.8 core:move-down (atom-text-editor.editor.mini)
     -0:14.0 core:confirm (atom-text-editor.editor.mini)
     -0:13.9 git-log:show (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "git-log": {}
}
```

### Installed Packages

```coffee
# User
git-log, v0.3.0
git-tab-status, v1.7.0
remember-session, v0.5.1

# Dev
No dev packages
```

**Comment by alex179ohm** [comment] 2015-07-07 11:23
I solved this by adding a conditional control on "data" and it resulting on an opened empty tab without errors, like this:
![screenshot from 2015-07-07 13 01 48](https://cloud.githubusercontent.com/assets/569010/8544874/4d5bf05c-24a9-11e5-9ff9-5debcb4034ae.png)

If it could be a reasonable fix for your too I've sent a PR with this comment, there are not more than 2 lines of code.

**Comment by phcloud** [comment] 2016-01-22 05:57
Uh,so, who can tell me that how to solve this problem?

**Comment by pycckuu** [comment] 2016-02-24 00:04
+1

**Comment by stEucalyptus** [comment] 2016-03-09 12:15
I was receiving this error because my git installation wasn't part of my PATH variable. Using Windows 7. A quick way to test if you're suffering the same issue is to try running `git --version` from cmd.exe (not the terminal that comes with git). If you get a message like _'git' is not recognized..._ try the options below. 

If you want to try this fix you have two options:

1. Add git to the PATH variable when installing git
2. Add git to the PATH variable manually after installing git

After either approach, try the cmd.exe test described above. If you get version details returned, git should now be part of your PATH. Restart Atom and retry running git-log.


**Option 1.** Add git to the PATH variable when installing git:
Install git for windows, for example from [https://git-scm.com/download/win](https://git-scm.com/download/win)

During the installation you should be prompted to adjust your PATH environment. 
Select an option that modifies the PATH, for example, the option to use git from the windows command prompt. 

**Option 2.** Add git to the PATH variable manually after installing git
You'll need the directory containing the git executable. Do a quick web search on how to add this directory to your system PATH variable. It's advisable to take a copy of your PATH variable before you make changes to it.

**Comment by brunolemos** [comment] 2016-04-14 18:48
I'm getting this error on a Mac (OS X El Capitan).

`[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.0
**System**: Mac OS X 10.11.4
**Thrown From**: [git-log](https://github.com/nikhilkalige/git-log) package, v0.4.1


### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At /Users/brunolemos/.atom/packages/git-log/lib/logparser.js:116

TypeError: Cannot read property 'split' of null
    at parse_git_log (/Users/brunolemos/.atom/packages/git-log/lib/logparser.js:116:20)
    at GitLogView.parser (/Users/brunolemos/.atom/packages/git-log/lib/git-log-view.js:117:16)
    at GitLogView.log_callback (/Users/brunolemos/.atom/packages/git-log/lib/git-log-view.js:69:10)
    at /Users/brunolemos/.atom/packages/git-log/lib/git-log-view.js:50:18
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -9:37.9.0 core:close (atom-text-editor.editor.is-focused)
     -9:36.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -9:36.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -9:35.6.0 core:close (atom-text-editor.editor.is-focused)
     -0:45.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:17.5.0 command-palette:toggle (div.package-detail.panels-item)
     -0:15.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:15.5.0 git-log:show (div.package-detail.panels-item)
     -0:07.2.0 core:cancel (div.git-log)
     -0:05.8.0 core:close (div.git-log)
     -0:04.6.0 command-palette:toggle (div.package-detail.panels-item)
     -0:03.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.0 git-log:show (div.package-detail.panels-item)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.2
atom-ternjs, v0.13.2
bottom-dock, v0.4.4
file-icons, v1.7.2
git-log, v0.4.1
gulp-manager, v0.2.19
highlight-selected, v0.11.2
language-graphql, v0.2.0
linter, v1.11.4
linter-eslint, v7.2.0
project-manager, v2.9.7
react, v0.15.0
todo-manager, v0.2.8

# Dev
No dev packages
```

`

**Comment by julmot** [comment] 2016-06-07 15:58
Same issue

**Atom Version**: 1.5.3
**Thrown From**: [git-log](https://github.com/nikhilkalige/git-log) package, v0.4.1


### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At W:\programs\Atom\.atom\packages\git-log\lib\logparser.js:116

TypeError: Cannot read property 'split' of null
    at parse_git_log (W:\programs\Atom\.atom\packages\git-log\lib\logparser.js:116:20)
    at GitLogView.parser (W:\programs\Atom\.atom\packages\git-log\lib\git-log-view.js:117:16)
    at GitLogView.log_callback (W:\programs\Atom\.atom\packages\git-log\lib\git-log-view.js:69:10)
    at W:\programs\Atom\.atom\packages\git-log\lib\git-log-view.js:50:18
    at triggerExitCallback (W:\programs\Atom\Program\resources\app.asar\src\buffered-process.js:213:47)
    at W:\programs\Atom\Program\resources\app.asar\src\buffered-process.js:227:18
    at Socket.<anonymous> (W:\programs\Atom\Program\resources\app.asar\src\buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -6:39.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -6:34.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:29.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -6:29.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -6:04.2.0 core:copy (atom-text-editor.editor.is-focused)
  2x -6:04.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:01.8.0 core:paste (atom-text-editor.editor.is-focused)
  2x -5:54.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:48.4.0 core:save (atom-text-editor.editor.is-focused)
  3x -4:34.2.0 core:close (atom-text-editor.editor.is-focused)
     -2:27.1.0 settings-view:install-packages-and-themes (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -2:24.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  7x -1:59.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:57.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:00.8.0 command-palette:toggle (div.package-detail.panels-item)
     -0:06.5.0 git-log:show (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false,
    "disabledPackages": [
      "language-mustache"
    ],
    "ignoredNames": [
      ".sass-cache",
      ".project",
      ".settings",
      ".buildpath",
      "project.pj",
      ".git"
    ],
    "projectHome": "W:\\projects\\_git\\"
  },
  "git-log": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.28
atom-handlebars, v1.3.0
docblockr, v0.7.3
git-log, v0.4.1
keyboard-localization, v1.4.16
minimap, v4.24.3
pigments, v0.29.1
prime-file-icons, v0.2.2

# Dev
No dev packages
```

**Comment by yidafu** [comment] 2017-09-12 23:54
Oh，thanks @stu-b-doo. I solved this issue by add git to the PATH variable. My OS is Windows10. If anyone see this and your PC is windows10 or Windows, you should try as what  @stu-b-doo say.

**Comment by bogdanostojic** [comment] 2018-01-19 23:01
Did a fresh install of Windows 10 and had the same issue.
First I did what @yidafu & @stu-b-doo  said and added git to PATH variable, but that didn't fix the error. I tried to commit but an error was thrown that I hadn't set my :
`config --global user.name` and `config --global user.email` .
 When I set those I didn't get any error's, and it looked like it fixed it.

**Comment by Inarus** [comment] 2018-07-26 19:45
The solution under win - https://stackoverflow.com/questions/4492979/git-is-not-recognized-as-an-internal-or-external-command
